x-base-service: &base-service
    platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
    restart: "no"
    profiles:
        - default

services:
  proxy:
    <<: *base-service
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/templates:/etc/nginx/templates:ro
    env_file: .env
    environment:
      GRAFANA_HOST: grafana
      GRAFANA_PORT: 3000
      LOKI_HOST: loki
      LOKI_PORT: 3100
    ports:
      - ${PROXY_LISTEN_PORT_GRAFANA}:${PROXY_LISTEN_PORT_GRAFANA}
      - ${PROXY_LISTEN_PORT_LOKI}:${PROXY_LISTEN_PORT_LOKI}
    depends_on:
      grafana:
        condition: service_started
      loki:
        condition: service_started
    profiles:
      - default

  proxy-grafana:
    <<: *base-service
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/templates/grafana.conf.template:/etc/nginx/templates/site.conf.template:ro
    env_file: .env
    environment:
      GRAFANA_HOST: grafana
      GRAFANA_PORT: 3000
    ports:
      - ${PROXY_LISTEN_PORT_GRAFANA}:${PROXY_LISTEN_PORT_GRAFANA}
    depends_on:
      grafana:
        condition: service_started
    profiles:
      - grafana

  grafana:
    <<: *base-service
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    profiles:
      - default
      - grafana

  loki:
    <<: *base-service
    image: grafana/loki:latest
    volumes:
      - ./configs/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    <<: *base-service
    image: grafana/promtail:latest
    volumes:
      - ./karaf-logs:/var/karaf-logs
      - ./configs/promtail-config.yaml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml

