auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 8388608  # 8 MB
  grpc_server_max_send_msg_size: 8388608  # 8 MB

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

ingester:
  max_chunk_age: 2h

schema_config:
  configs:
    - from: 2023-01-05
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v12
      store: tsdb

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  split_queries_by_interval: 0
  max_streams_per_user: 10000
