auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
        
# max_chunk_age см. здесь: https://grafana.com/docs/loki/latest/configure/#accept-out-of-order-writes
# Насколько далеко в прошлом могут быть принятые записи журнала.
# max_chunk_age по умолчанию 2 часа.
# ==========================================
# Пример если max_chunk_age не задан (равен 2 по умолчанию):
# ==========================================
# Текущая дата: 01.03.2024 12:00:00
# Нужно учитывать, что UTC - это +3 часа
# ------------------------------------------
# Логи:
# 01.03.2024 05:00:00 лог 1 - не будет выведен т.к. 5+3=8, 12-8=4, 4 часа - старше 2х часов от текущей даты
# 01.03.2024 06:00:00 лог 1 - не будет выведен т.к. 6+3=9, 12-9=3, 3 часа - старше 2х часов от текущей даты
# 01.03.2024 07:00:00 лог 1 - будет выведен т.к. 7+3=10, 12-10=2, 2 часа - не старше 2х часов от текущей даты
# 01.03.2024 08:00:00 лог 1 - будет выведен т.к. 8+3=11, 12-11=1, 1 часа - не старше 2х часов от текущей даты
# 01.03.2024 09:00:00 лог 1 - будет выведен т.к. 9+3=12, 12-12=0, задержки нет - не старше 2х часов от текущей даты
# 01.03.2024 10:00:00 лог 1 - не будет выведен т.к. 10+3=13, 13:00 - это уже в будущем по
#                                сравнению с 12:00. Будет ошибка has timestamp too new: 2024-03-01T10:00:00Z
ingester:
  max_chunk_age: 4h

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  split_queries_by_interval: 0

