server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: karaf-logs
    static_configs:
      - targets:
          - karaf-logs
        labels:
          job: karaf-logs
          __path__: /var/karaf-logs/karaf*.log*
    pipeline_stages:
      - match:
          selector: '{job="karaf-logs"}'
          stages:
            - multiline:
                firstline: '^\d{4}-\d{2}-\d{2}[\sT]\d{2}:\d{2}:\d{2},\d{3}'
                max_lines: 128
                max_wait_time: 3s
            - regex:
                expression: '^(?P<time>.+?)\s+\|\s+(?P<log_level>\w+)'
            - timestamp:
                format: 2006-01-02T15:04:05,000
                source: time
                location: Europe/Moscow
            - regex:
                expression: '(?P<xml_status>[0-9]*)<\/status>'
            - regex:
                expression: 'ResponseCode:\s(?P<response_code>[0-9]*)'
            - labels:
                log_level:
                xml_status:
                response_code:
            - labeldrop:
                - time

#promtail --dry-run --inspect --config.file=/etc/promtail/promtail-config.yml
